development:
  adapter:  mysql2
  database: swift_development
  host:     localhost
  username: root
  password:
  encoding: utf8
  pool: 5

production:
  adapter:  mysql2
  database: swift_development
  host:     localhost
  username: root
  password:
  encoding: utf8
  pool: 5
